service: my-s3-service

custom:
  wsgi:
    app: app.app
    packRequirements: false  
  bucketName: 4e109a3f-905a-480b-9386-8eaef360f0fc

provider:
  name: aws
  runtime: python3.10
  region: us-west-2
  environment:
    VARIABLE_1: supersecret99
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"


package:
  individually: true
  patterns:
    - app.py
    - requirements.txt
    - venv/**
    - node_modules/**
plugins:
  - serverless-s3-deploy
  - serverless-python-requirements
  - serverless-wsgi

resources:
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}    
        AccessControl: Private
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'



