name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    name: App Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  Secret:
    name: Secretscan
    uses: ./.github/workflows/secrets.yml
    secrets: inherit

  SCA:
    needs: Build
    name: SCA
    uses: ./.github/workflows/SCA.yml
    permissions:
      security-events: write
    secrets: inherit

  SAST:
    needs: Build
    name: SAST
    uses: ./.github/workflows/SAST.yml
    permissions:
      security-events: write
    secrets: inherit

  Deploy:
    needs: [Build,SAST,SCA]
    name: Deployapp_scanzap
    uses: ./.github/workflows/deploy.yml
    secrets: inherit




