name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: App Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  Secret:
    name: Secret
    uses: ./.github/workflows/secrets.yml
    secrets: inherit

  SCA:
    needs: build
    name: SCA
    uses: ./.github/workflows/SCA.yml
    secrets: inherit

  SAST:
    needs: build
    name: SAST
    uses: ./.github/workflows/SAST.yml
    secrets: inherit

  Deploy:
    needs: build
    name: Deployapp
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  DAST:
    needs: [build,Deploy]
    name: OWASP ZAP Scan
    uses: ./.github/workflows/DAST.yml
    secrets: inherit

