name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    name: App Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  Secret:
    name: Secretscan
    uses: ./.github/workflows/secrets.yml
    secrets: inherit



  Deploy:
    needs: [Build]
    name: Deployapp_scanzap
    uses: ./.github/workflows/deploy.yml
    secrets: inherit




