name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    name: App Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  remove:
    name: removeapp
    uses: ./.github/workflows/remove.yml
    secrets: inherit



