name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: App Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  SCA:
    needs: build
    name: SCA
    uses: ./.github/workflows/SCA.yml
    secrets: inherit

 

