name: Dast

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Owasp_zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: https://qhsionkph0.execute-api.us-west-2.amazonaws.com/dev
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: zap_scan
          path: artifacts
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-west-2

      - name: Upload zap report to S3
        run: |
          aws s3 cp artifacts/report_json.json s3://owaspzapreports/Owasp-zap-report.json --debug
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

