name: OWASP ZAP Scan

on:
  workflow_dispatch:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          token: ${{ secrets.TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://cokb9gdxk2.execute-api.us-west-2.amazonaws.com/dev'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
      - name: Upload zap report
        uses: actions/upload-artifact@v3
        with:
          name: Dast-report.json
          path: Dast-report.json