name: SAST 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sast:
    runs-on: ubuntu-latest
    
    name: SAST python project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
