name: SAST 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  semgrep-scan:

    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - name: Clone application source code
        uses: actions/checkout@v3

      - name: Full scan
        run: |
          semgrep \
            --sarif --output report-semgrep.sarif \
            --metrics=off \
            --config="p/default"

      - name: Save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: report-semgrep.sarif
          path: report-semgrep.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report-semgrep.sarif


