name: SAST 

on:
  workflow_dispatch:
  workflow_call:

jobs:

  semgrep-scan:
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:

        # step 1
        - name: clone application source code
          uses: actions/checkout@v3

        # step 2
        - name: full scan
          run: |
            semgrep \
              --sarif --output report-semgrep.sarif \
              --metrics=off \
              --config="p/default"

        # step 3
        
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@v3
          with:
            name: report-semgrep.sarif
            path: report-semgrep.sarif
            
        # step 4
        - name: Download report
          uses: actions/download-artifact@v2
          with: 
            name: report-semgrep.sarif
  
  Bandit_scan:
  name: Run Bandit Scan
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit Scan
      run: bandit -ll -ii -r . -f sarif -o bandit-report.sarif

    - name: Upload Bandit Scan Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.sarif