name: SAST 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  SAST-CodeQL:
    name: SAST-CodeQL
    runs-on: ubuntu-latest
    permissions:
     contents: read
      
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyse@v2
        with:
          languages: python
