name: SCA 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    runs-on: ubuntu-latest
    
    name: SCA python project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
        with:
           command: test --sarif
           args: --sarif-file-output=snyk_report.sarif
    
        # step 3
        
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
            name: snyk_report.sarif
            path: snyk_report.sarif
            
        # step 4
      - name: Download report
        uses: actions/download-artifact@v2
        with: 
            name: snyk_report.sarif



