name: SCA 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    strategy: 
      fail-fast: false
      matrix:
        os: ["ubunto-20.04"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    
    name: SCA python project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: SCA (CRDA) Scan
        id: crda_scan
        uses: redhat-actions/crda@v1.2
        with:
          manifest_file: ${{ matrix.manifest_file }}
          snyk_token: ${{ secrets.OUR_SNYK_Key}}
          fail_on: never

      - name: Print JSON analysis report
        if: ${{ always() && steps.scan.outputs.crda_report_json}}
        run: cat ${{ steps.scan.outputs.crda_report_json}}
      
      - name: Print SARIF analysis report
        if: ${{ always() && steps.scan.outputs.crda_report_sarif}}
        run: cat ${{ steps.scan.outputs.crda_report_sarif}}

      - name: Print Report Link
        run: echo ${{ steps.san.outputs.report_link }}
      
      - name: Print Artifact Name
        run: echo ${{ steps.scan.outputs.artifact_name}}

