name: SCA 

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    runs-on: ubuntu-latest
    
    name: SCA python project
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
        


      - name: Print JSON analysis report
        if: ${{ always() && steps.scan.outputs.snyk_report_json}}
        run: cat ${{ steps.scan.outputs.snyk_report_json}}
      
      - name: Print SARIF analysis report
        if: ${{ always() && steps.scan.outputs.snyk_report_sarif}}
        run: cat ${{ steps.scan.outputs.snyk_report_sarif}}

      - name: Print Report Link
        run: echo ${{ steps.scan.outputs.report_link }}
      
      - name: Print Artifact Name
        run: echo ${{ steps.scan.outputs.artifact_name}}

