name: Sca

on:
  workflow_dispatch:
  workflow_call:

jobs:
  sca:
    runs-on: ubuntu-latest
    
    name: dependency-check-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
           SNYK_TOKEN: ${{ secrets.OUR_SNYK_KEY }}
        with:
           command: test --all-projects --sarif
           args: --sarif-file-output=dependency-check.sarif
    
        # step 3
        
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
            name: dependency-check_report.sarif
            path: dependency-check_report.sarif
            




